// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: magicMath/magic_math.proto

package magicMath

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MagicMath_MagicAdd_FullMethodName      = "/shared.MagicMath/MagicAdd"
	MagicMath_MagicSubtract_FullMethodName = "/shared.MagicMath/MagicSubtract"
	MagicMath_MagicFindMin_FullMethodName  = "/shared.MagicMath/MagicFindMin"
	MagicMath_MagicFindMax_FullMethodName  = "/shared.MagicMath/MagicFindMax"
	MagicMath_GetAddCount_FullMethodName   = "/shared.MagicMath/GetAddCount"
	MagicMath_GetSubCount_FullMethodName   = "/shared.MagicMath/GetSubCount"
	MagicMath_GetMinCount_FullMethodName   = "/shared.MagicMath/GetMinCount"
	MagicMath_GetMaxCount_FullMethodName   = "/shared.MagicMath/GetMaxCount"
)

// MagicMathClient is the client API for MagicMath service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MagicMathClient interface {
	// These four remote functions are what the client will use to call the server to do the math.
	MagicAdd(ctx context.Context, in *DoubleTerms, opts ...grpc.CallOption) (*DoubleResult, error)
	MagicSubtract(ctx context.Context, in *DoubleTerms, opts ...grpc.CallOption) (*DoubleResult, error)
	MagicFindMin(ctx context.Context, in *IntTerms, opts ...grpc.CallOption) (*IntResult, error)
	MagicFindMax(ctx context.Context, in *IntTerms, opts ...grpc.CallOption) (*IntResult, error)
	// These four remote functions will be used by the client to get the counters from the server.
	GetAddCount(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Count, error)
	GetSubCount(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Count, error)
	GetMinCount(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Count, error)
	GetMaxCount(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Count, error)
}

type magicMathClient struct {
	cc grpc.ClientConnInterface
}

func NewMagicMathClient(cc grpc.ClientConnInterface) MagicMathClient {
	return &magicMathClient{cc}
}

func (c *magicMathClient) MagicAdd(ctx context.Context, in *DoubleTerms, opts ...grpc.CallOption) (*DoubleResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DoubleResult)
	err := c.cc.Invoke(ctx, MagicMath_MagicAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magicMathClient) MagicSubtract(ctx context.Context, in *DoubleTerms, opts ...grpc.CallOption) (*DoubleResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DoubleResult)
	err := c.cc.Invoke(ctx, MagicMath_MagicSubtract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magicMathClient) MagicFindMin(ctx context.Context, in *IntTerms, opts ...grpc.CallOption) (*IntResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntResult)
	err := c.cc.Invoke(ctx, MagicMath_MagicFindMin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magicMathClient) MagicFindMax(ctx context.Context, in *IntTerms, opts ...grpc.CallOption) (*IntResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntResult)
	err := c.cc.Invoke(ctx, MagicMath_MagicFindMax_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magicMathClient) GetAddCount(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Count, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Count)
	err := c.cc.Invoke(ctx, MagicMath_GetAddCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magicMathClient) GetSubCount(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Count, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Count)
	err := c.cc.Invoke(ctx, MagicMath_GetSubCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magicMathClient) GetMinCount(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Count, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Count)
	err := c.cc.Invoke(ctx, MagicMath_GetMinCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magicMathClient) GetMaxCount(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Count, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Count)
	err := c.cc.Invoke(ctx, MagicMath_GetMaxCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MagicMathServer is the server API for MagicMath service.
// All implementations must embed UnimplementedMagicMathServer
// for forward compatibility.
type MagicMathServer interface {
	// These four remote functions are what the client will use to call the server to do the math.
	MagicAdd(context.Context, *DoubleTerms) (*DoubleResult, error)
	MagicSubtract(context.Context, *DoubleTerms) (*DoubleResult, error)
	MagicFindMin(context.Context, *IntTerms) (*IntResult, error)
	MagicFindMax(context.Context, *IntTerms) (*IntResult, error)
	// These four remote functions will be used by the client to get the counters from the server.
	GetAddCount(context.Context, *Empty) (*Count, error)
	GetSubCount(context.Context, *Empty) (*Count, error)
	GetMinCount(context.Context, *Empty) (*Count, error)
	GetMaxCount(context.Context, *Empty) (*Count, error)
	mustEmbedUnimplementedMagicMathServer()
}

// UnimplementedMagicMathServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMagicMathServer struct{}

func (UnimplementedMagicMathServer) MagicAdd(context.Context, *DoubleTerms) (*DoubleResult, error) {
	return nil, status.Error(codes.Unimplemented, "method MagicAdd not implemented")
}
func (UnimplementedMagicMathServer) MagicSubtract(context.Context, *DoubleTerms) (*DoubleResult, error) {
	return nil, status.Error(codes.Unimplemented, "method MagicSubtract not implemented")
}
func (UnimplementedMagicMathServer) MagicFindMin(context.Context, *IntTerms) (*IntResult, error) {
	return nil, status.Error(codes.Unimplemented, "method MagicFindMin not implemented")
}
func (UnimplementedMagicMathServer) MagicFindMax(context.Context, *IntTerms) (*IntResult, error) {
	return nil, status.Error(codes.Unimplemented, "method MagicFindMax not implemented")
}
func (UnimplementedMagicMathServer) GetAddCount(context.Context, *Empty) (*Count, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAddCount not implemented")
}
func (UnimplementedMagicMathServer) GetSubCount(context.Context, *Empty) (*Count, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubCount not implemented")
}
func (UnimplementedMagicMathServer) GetMinCount(context.Context, *Empty) (*Count, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMinCount not implemented")
}
func (UnimplementedMagicMathServer) GetMaxCount(context.Context, *Empty) (*Count, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMaxCount not implemented")
}
func (UnimplementedMagicMathServer) mustEmbedUnimplementedMagicMathServer() {}
func (UnimplementedMagicMathServer) testEmbeddedByValue()                   {}

// UnsafeMagicMathServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MagicMathServer will
// result in compilation errors.
type UnsafeMagicMathServer interface {
	mustEmbedUnimplementedMagicMathServer()
}

func RegisterMagicMathServer(s grpc.ServiceRegistrar, srv MagicMathServer) {
	// If the following call panics, it indicates UnimplementedMagicMathServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MagicMath_ServiceDesc, srv)
}

func _MagicMath_MagicAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoubleTerms)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagicMathServer).MagicAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagicMath_MagicAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagicMathServer).MagicAdd(ctx, req.(*DoubleTerms))
	}
	return interceptor(ctx, in, info, handler)
}

func _MagicMath_MagicSubtract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoubleTerms)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagicMathServer).MagicSubtract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagicMath_MagicSubtract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagicMathServer).MagicSubtract(ctx, req.(*DoubleTerms))
	}
	return interceptor(ctx, in, info, handler)
}

func _MagicMath_MagicFindMin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntTerms)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagicMathServer).MagicFindMin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagicMath_MagicFindMin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagicMathServer).MagicFindMin(ctx, req.(*IntTerms))
	}
	return interceptor(ctx, in, info, handler)
}

func _MagicMath_MagicFindMax_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntTerms)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagicMathServer).MagicFindMax(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagicMath_MagicFindMax_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagicMathServer).MagicFindMax(ctx, req.(*IntTerms))
	}
	return interceptor(ctx, in, info, handler)
}

func _MagicMath_GetAddCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagicMathServer).GetAddCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagicMath_GetAddCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagicMathServer).GetAddCount(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MagicMath_GetSubCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagicMathServer).GetSubCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagicMath_GetSubCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagicMathServer).GetSubCount(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MagicMath_GetMinCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagicMathServer).GetMinCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagicMath_GetMinCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagicMathServer).GetMinCount(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MagicMath_GetMaxCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagicMathServer).GetMaxCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagicMath_GetMaxCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagicMathServer).GetMaxCount(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// MagicMath_ServiceDesc is the grpc.ServiceDesc for MagicMath service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MagicMath_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shared.MagicMath",
	HandlerType: (*MagicMathServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MagicAdd",
			Handler:    _MagicMath_MagicAdd_Handler,
		},
		{
			MethodName: "MagicSubtract",
			Handler:    _MagicMath_MagicSubtract_Handler,
		},
		{
			MethodName: "MagicFindMin",
			Handler:    _MagicMath_MagicFindMin_Handler,
		},
		{
			MethodName: "MagicFindMax",
			Handler:    _MagicMath_MagicFindMax_Handler,
		},
		{
			MethodName: "GetAddCount",
			Handler:    _MagicMath_GetAddCount_Handler,
		},
		{
			MethodName: "GetSubCount",
			Handler:    _MagicMath_GetSubCount_Handler,
		},
		{
			MethodName: "GetMinCount",
			Handler:    _MagicMath_GetMinCount_Handler,
		},
		{
			MethodName: "GetMaxCount",
			Handler:    _MagicMath_GetMaxCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "magicMath/magic_math.proto",
}
