// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: shared/math_server.proto

package shared

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DoubleTerms struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TermOne       float64                `protobuf:"fixed64,1,opt,name=termOne,proto3" json:"termOne,omitempty"`
	TermTwo       float64                `protobuf:"fixed64,2,opt,name=termTwo,proto3" json:"termTwo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoubleTerms) Reset() {
	*x = DoubleTerms{}
	mi := &file_shared_math_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoubleTerms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleTerms) ProtoMessage() {}

func (x *DoubleTerms) ProtoReflect() protoreflect.Message {
	mi := &file_shared_math_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleTerms.ProtoReflect.Descriptor instead.
func (*DoubleTerms) Descriptor() ([]byte, []int) {
	return file_shared_math_server_proto_rawDescGZIP(), []int{0}
}

func (x *DoubleTerms) GetTermOne() float64 {
	if x != nil {
		return x.TermOne
	}
	return 0
}

func (x *DoubleTerms) GetTermTwo() float64 {
	if x != nil {
		return x.TermTwo
	}
	return 0
}

type DoubleResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float64                `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoubleResult) Reset() {
	*x = DoubleResult{}
	mi := &file_shared_math_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoubleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleResult) ProtoMessage() {}

func (x *DoubleResult) ProtoReflect() protoreflect.Message {
	mi := &file_shared_math_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleResult.ProtoReflect.Descriptor instead.
func (*DoubleResult) Descriptor() ([]byte, []int) {
	return file_shared_math_server_proto_rawDescGZIP(), []int{1}
}

func (x *DoubleResult) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

type IntTerms struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TermOne       int64                  `protobuf:"zigzag64,1,opt,name=termOne,proto3" json:"termOne,omitempty"`
	TermTwo       int64                  `protobuf:"zigzag64,2,opt,name=termTwo,proto3" json:"termTwo,omitempty"`
	TermThree     int64                  `protobuf:"zigzag64,3,opt,name=termThree,proto3" json:"termThree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntTerms) Reset() {
	*x = IntTerms{}
	mi := &file_shared_math_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntTerms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntTerms) ProtoMessage() {}

func (x *IntTerms) ProtoReflect() protoreflect.Message {
	mi := &file_shared_math_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntTerms.ProtoReflect.Descriptor instead.
func (*IntTerms) Descriptor() ([]byte, []int) {
	return file_shared_math_server_proto_rawDescGZIP(), []int{2}
}

func (x *IntTerms) GetTermOne() int64 {
	if x != nil {
		return x.TermOne
	}
	return 0
}

func (x *IntTerms) GetTermTwo() int64 {
	if x != nil {
		return x.TermTwo
	}
	return 0
}

func (x *IntTerms) GetTermThree() int64 {
	if x != nil {
		return x.TermThree
	}
	return 0
}

type IntResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int64                  `protobuf:"zigzag64,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntResult) Reset() {
	*x = IntResult{}
	mi := &file_shared_math_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntResult) ProtoMessage() {}

func (x *IntResult) ProtoReflect() protoreflect.Message {
	mi := &file_shared_math_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntResult.ProtoReflect.Descriptor instead.
func (*IntResult) Descriptor() ([]byte, []int) {
	return file_shared_math_server_proto_rawDescGZIP(), []int{3}
}

func (x *IntResult) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_shared_math_server_proto protoreflect.FileDescriptor

const file_shared_math_server_proto_rawDesc = "" +
	"\n" +
	"\x18shared/math_server.proto\x12\x06shared\"A\n" +
	"\vDoubleTerms\x12\x18\n" +
	"\atermOne\x18\x01 \x01(\x01R\atermOne\x12\x18\n" +
	"\atermTwo\x18\x02 \x01(\x01R\atermTwo\"&\n" +
	"\fDoubleResult\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x01R\x06result\"\\\n" +
	"\bIntTerms\x12\x18\n" +
	"\atermOne\x18\x01 \x01(\x12R\atermOne\x12\x18\n" +
	"\atermTwo\x18\x02 \x01(\x12R\atermTwo\x12\x1c\n" +
	"\ttermThree\x18\x03 \x01(\x12R\ttermThree\"#\n" +
	"\tIntResult\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x12R\x06result2\xe9\x01\n" +
	"\n" +
	"MathServer\x125\n" +
	"\bMagicAdd\x12\x13.shared.DoubleTerms\x1a\x14.shared.DoubleResult\x12:\n" +
	"\rMagicSubtract\x12\x13.shared.DoubleTerms\x1a\x14.shared.DoubleResult\x123\n" +
	"\fMagicFindMin\x12\x10.shared.IntTerms\x1a\x11.shared.IntResult\x123\n" +
	"\fMagicFindMax\x12\x10.shared.IntTerms\x1a\x11.shared.IntResultB\n" +
	"Z\b./sharedb\x06proto3"

var (
	file_shared_math_server_proto_rawDescOnce sync.Once
	file_shared_math_server_proto_rawDescData []byte
)

func file_shared_math_server_proto_rawDescGZIP() []byte {
	file_shared_math_server_proto_rawDescOnce.Do(func() {
		file_shared_math_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_math_server_proto_rawDesc), len(file_shared_math_server_proto_rawDesc)))
	})
	return file_shared_math_server_proto_rawDescData
}

var file_shared_math_server_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shared_math_server_proto_goTypes = []any{
	(*DoubleTerms)(nil),  // 0: shared.DoubleTerms
	(*DoubleResult)(nil), // 1: shared.DoubleResult
	(*IntTerms)(nil),     // 2: shared.IntTerms
	(*IntResult)(nil),    // 3: shared.IntResult
}
var file_shared_math_server_proto_depIdxs = []int32{
	0, // 0: shared.MathServer.MagicAdd:input_type -> shared.DoubleTerms
	0, // 1: shared.MathServer.MagicSubtract:input_type -> shared.DoubleTerms
	2, // 2: shared.MathServer.MagicFindMin:input_type -> shared.IntTerms
	2, // 3: shared.MathServer.MagicFindMax:input_type -> shared.IntTerms
	1, // 4: shared.MathServer.MagicAdd:output_type -> shared.DoubleResult
	1, // 5: shared.MathServer.MagicSubtract:output_type -> shared.DoubleResult
	3, // 6: shared.MathServer.MagicFindMin:output_type -> shared.IntResult
	3, // 7: shared.MathServer.MagicFindMax:output_type -> shared.IntResult
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_math_server_proto_init() }
func file_shared_math_server_proto_init() {
	if File_shared_math_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_math_server_proto_rawDesc), len(file_shared_math_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_math_server_proto_goTypes,
		DependencyIndexes: file_shared_math_server_proto_depIdxs,
		MessageInfos:      file_shared_math_server_proto_msgTypes,
	}.Build()
	File_shared_math_server_proto = out.File
	file_shared_math_server_proto_goTypes = nil
	file_shared_math_server_proto_depIdxs = nil
}
