// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: shared/math_server.proto

package shared

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MathServer_MagicAdd_FullMethodName      = "/shared.MathServer/MagicAdd"
	MathServer_MagicSubtract_FullMethodName = "/shared.MathServer/MagicSubtract"
	MathServer_MagicFindMin_FullMethodName  = "/shared.MathServer/MagicFindMin"
	MathServer_MagicFindMax_FullMethodName  = "/shared.MathServer/MagicFindMax"
)

// MathServerClient is the client API for MathServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MathServerClient interface {
	MagicAdd(ctx context.Context, in *DoubleTerms, opts ...grpc.CallOption) (*DoubleResult, error)
	MagicSubtract(ctx context.Context, in *DoubleTerms, opts ...grpc.CallOption) (*DoubleResult, error)
	MagicFindMin(ctx context.Context, in *IntTerms, opts ...grpc.CallOption) (*IntResult, error)
	MagicFindMax(ctx context.Context, in *IntTerms, opts ...grpc.CallOption) (*IntResult, error)
}

type mathServerClient struct {
	cc grpc.ClientConnInterface
}

func NewMathServerClient(cc grpc.ClientConnInterface) MathServerClient {
	return &mathServerClient{cc}
}

func (c *mathServerClient) MagicAdd(ctx context.Context, in *DoubleTerms, opts ...grpc.CallOption) (*DoubleResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DoubleResult)
	err := c.cc.Invoke(ctx, MathServer_MagicAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mathServerClient) MagicSubtract(ctx context.Context, in *DoubleTerms, opts ...grpc.CallOption) (*DoubleResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DoubleResult)
	err := c.cc.Invoke(ctx, MathServer_MagicSubtract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mathServerClient) MagicFindMin(ctx context.Context, in *IntTerms, opts ...grpc.CallOption) (*IntResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntResult)
	err := c.cc.Invoke(ctx, MathServer_MagicFindMin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mathServerClient) MagicFindMax(ctx context.Context, in *IntTerms, opts ...grpc.CallOption) (*IntResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntResult)
	err := c.cc.Invoke(ctx, MathServer_MagicFindMax_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MathServerServer is the server API for MathServer service.
// All implementations must embed UnimplementedMathServerServer
// for forward compatibility.
type MathServerServer interface {
	MagicAdd(context.Context, *DoubleTerms) (*DoubleResult, error)
	MagicSubtract(context.Context, *DoubleTerms) (*DoubleResult, error)
	MagicFindMin(context.Context, *IntTerms) (*IntResult, error)
	MagicFindMax(context.Context, *IntTerms) (*IntResult, error)
	mustEmbedUnimplementedMathServerServer()
}

// UnimplementedMathServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMathServerServer struct{}

func (UnimplementedMathServerServer) MagicAdd(context.Context, *DoubleTerms) (*DoubleResult, error) {
	return nil, status.Error(codes.Unimplemented, "method MagicAdd not implemented")
}
func (UnimplementedMathServerServer) MagicSubtract(context.Context, *DoubleTerms) (*DoubleResult, error) {
	return nil, status.Error(codes.Unimplemented, "method MagicSubtract not implemented")
}
func (UnimplementedMathServerServer) MagicFindMin(context.Context, *IntTerms) (*IntResult, error) {
	return nil, status.Error(codes.Unimplemented, "method MagicFindMin not implemented")
}
func (UnimplementedMathServerServer) MagicFindMax(context.Context, *IntTerms) (*IntResult, error) {
	return nil, status.Error(codes.Unimplemented, "method MagicFindMax not implemented")
}
func (UnimplementedMathServerServer) mustEmbedUnimplementedMathServerServer() {}
func (UnimplementedMathServerServer) testEmbeddedByValue()                    {}

// UnsafeMathServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MathServerServer will
// result in compilation errors.
type UnsafeMathServerServer interface {
	mustEmbedUnimplementedMathServerServer()
}

func RegisterMathServerServer(s grpc.ServiceRegistrar, srv MathServerServer) {
	// If the following call panics, it indicates UnimplementedMathServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MathServer_ServiceDesc, srv)
}

func _MathServer_MagicAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoubleTerms)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServerServer).MagicAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MathServer_MagicAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServerServer).MagicAdd(ctx, req.(*DoubleTerms))
	}
	return interceptor(ctx, in, info, handler)
}

func _MathServer_MagicSubtract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoubleTerms)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServerServer).MagicSubtract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MathServer_MagicSubtract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServerServer).MagicSubtract(ctx, req.(*DoubleTerms))
	}
	return interceptor(ctx, in, info, handler)
}

func _MathServer_MagicFindMin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntTerms)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServerServer).MagicFindMin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MathServer_MagicFindMin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServerServer).MagicFindMin(ctx, req.(*IntTerms))
	}
	return interceptor(ctx, in, info, handler)
}

func _MathServer_MagicFindMax_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntTerms)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServerServer).MagicFindMax(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MathServer_MagicFindMax_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServerServer).MagicFindMax(ctx, req.(*IntTerms))
	}
	return interceptor(ctx, in, info, handler)
}

// MathServer_ServiceDesc is the grpc.ServiceDesc for MathServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MathServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shared.MathServer",
	HandlerType: (*MathServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MagicAdd",
			Handler:    _MathServer_MagicAdd_Handler,
		},
		{
			MethodName: "MagicSubtract",
			Handler:    _MathServer_MagicSubtract_Handler,
		},
		{
			MethodName: "MagicFindMin",
			Handler:    _MathServer_MagicFindMin_Handler,
		},
		{
			MethodName: "MagicFindMax",
			Handler:    _MathServer_MagicFindMax_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shared/math_server.proto",
}
